version: '3.1'

services:

  postgres:
    restart: always
    image: postgres:11.4-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=seven23
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=seven23

  seven23_server:
    build: .
    image: seven23_server:latest
    depends_on:
     - postgres
    ports:
     - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://seven23:password@postgres:5432/seven23
      - CONTACT_EMAI=admin@seven23.io
      - SECRET_KEY="MY-SECRET_KEY"
      - ALLOW_ACCOUNT_CREATION="True"
      - DEBUG="True"
